# Generated by Django 2.1.3 on 2019-04-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='产品列表',
            name='类别',
        ),
        migrations.RemoveField(
            model_name='商品类别表',
            name='类别',
        ),
        migrations.AddField(
            model_name='产品列表',
            name='描述',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='商品类别表',
            name='描述',
            field=models.TextField(blank=True),
        ),
    ]
